version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: transcriptor_db
    volumes:
      - ./mongo-data:/data/db
    networks:
      - transcriptor-net
    # sin "ports" — ya no es alcanzable desde fuera del servidor,
    # solo desde los otros contenedores por la red interna

  backend:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: transcriptor_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/informes_medicos_db
    depends_on:
      - mongodb
    networks:
      - transcriptor-net

  frontend:
    build: 
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: transcriptor_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - transcriptor-net

networks:
  transcriptor-net:
    driver: bridge