services:
  mongodb:
    image: mongo:6.0
    container_name: transcriptor_db
    command: ["--auth"]
    volumes:
      - ./mongo-data:/data/db
    networks:
      - transcriptor-net

  backend:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: transcriptor_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://app_backend:${MONGO_APP_PASSWORD}@mongodb:27017/informes_medicos_db?authSource=informes_medicos_db
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    volumes:
      - ./google-credentials.json:/app/google-credentials.json
    depends_on:
      - mongodb
    networks:
      - transcriptor-net

  frontend:
    build: 
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: transcriptor_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - transcriptor-net

networks:
  transcriptor-net:
    driver: bridge