spring.application.name=Transcriptor

spring.data.mongodb.uri=mongodb://localhost:27017/informes_medicos_db

# Mostrar consultas en consola (muy útil para debuggear)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG