spring.application.name=Transcriptor

spring.data.mongodb.uri=mongodb://localhost:27017/informes_medicos_db

# Mostrar consultas en consola (muy útil para debuggear)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


# --- CONFIGURACIÓN DE VERTEX AI (PRIVACIDAD MÉDICA) ---
spring.ai.vertex.ai.gemini.project-id=transcriptor-ia-489921
spring.ai.vertex.ai.gemini.location=us-central1

# Le decimos a Spring Boot dónde está tu llave JSON (la misma del audio)
spring.cloud.gcp.credentials.location=classpath:google-credentials.json
