spring.application.name=Transcriptor

spring.data.mongodb.uri=mongodb://localhost:27017/informes_medicos_db

# Mostrar consultas en consola (muy útil para debuggear)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Credenciales para Vertex AI (El Cerebro)
spring.ai.vertex.ai.gemini.credentials-uri=classpath:google-credentials.json
spring.ai.vertex.ai.gemini.project-id=transcriptor-ia-489921
spring.ai.vertex.ai.gemini.location=us-central1